# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46fffa33710710c0b1f3eceb9af6996a3a7be7ffef5137d3aeca3f8ab4758e9c66c9c61830edfc7aa01a62fa1f9df9430baa9447ecea9d140e0c3b4f18144d0

test:
  secret_key_base: 92414fb754b8243f1e10b24c1ac3f3eb9b527614c70c476f9956e3cbfcafbf8aecb3f08a1d71fc9420cf3be7c0b2e863cfa8fa312812fa5822887d766ce017f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
