# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4ff9cc95e02253a6a917858b154ce14f4f5764b01c3ab9ffa591d9a0fc0be7f997aafcb5512da52ad4555479c1fd37ca1bdf698966180457d646e45926b73c

test:
  secret_key_base: b3fd99051b2ae287b76df19fe49ef890bce29ecf73901fa36ee1bf07801e742fd5a2a9220578a700473da42383083d98f2fc1eed71321263ca33620048c37d2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
