# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ccfb0fc2d4ea8e392592f2ed291a7b15f055eb2341f40347b6b08b075615de6624779c059cbba81f55163e43739e1272f9b915171b88ba864f65d2650e58d1

test:
  secret_key_base: 0403e6b5a5e31f8a5d2d50ad97946f05d52ff30f546b3f79deb80fd8e0776e1da6e4bcaa69c3020c0ff32af07e99f1440ff5847afe227c9ba45fed1b3fd57f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
